version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.5.0
  environment:
    GOROOT: /home/circleci/goroot
    GOPATH: /home/circleci/go
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Get dependencies
          command: |
            PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
            export PATH

            echo "Cleaning"
            rm -Rf build dist || true

            mkdir -p ${GOPATH}
            rm -Rf ${GOROOT} || true

            sudo apt-get update
            sudo apt-get install -y cmake ruby ruby-dev rubygems build-essential wget
            sudo gem install --no-ri --no-rdoc fpm
      - run:
          name: test
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: |
          cd ${HOME}

          PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
          VERSION=$(node repo/scripts/get-version.js)
          export PATH VERSION

          rm -Rf ${GOROOT} || true

          sudo apt-get update
          sudo apt-get install -y cmake ruby ruby-dev rubygems build-essential wget zip
          sudo gem install --no-ri --no-rdoc fpm

          cd ${HOME}
          mkdir -p download
          cd download
          wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
          tar xvfz go1.10.3.linux-amd64.tar.gz
          mv go ../goroot

          go get github.com/tcnksm/ghr

          cd ~/repo
          echo "Cleaning"
          rm -Rf build dist || true

          echo "Making installers"
          npm run installers

          cd ~/repo/build
          zip artifacts/cxxpods-macos.zip cxxpods-macos
          zip artifacts/cxxpods-linux.zip cxxpods-linux

          cd ~/repo
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate v${VERSION} ./build/artifacts/
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /feature.*/
